name: apple_search_ads
description: A Dart package to interact with the Apple Search Ads API using OAuth 2.0 authentication.
version: 0.0.2
homepage:
repository: https://github.com/emirtoprak/apple_search_ads
issue_tracker: https://github.com/emirtoprak/apple_search_ads/issues

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  dart_jsonwebtoken: ^2.14.0
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

license: MIT