name: apple_search_ads
description: A Dart package to interact with the Apple Search Ads API using OAuth 2.0 authentication.
version: 0.0.6
homepage:
repository: https://github.com/emirtoprak/apple_search_ads
issue_tracker: https://github.com/emirtoprak/apple_search_ads/issues

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dart_jsonwebtoken: ^2.14.0
  flutter:
    sdk: flutter
  flutter_asa_attribution: ^0.0.3
  http: ^1.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

license: MIT